### ISSUE TITLE
When pasting a multi-line WKT in the WKT field an error is displayed and the WKT is not displayed on the map.

### ISSUE THREAD

**Issue by koendecock** [pieterprovoost/wktmap#16]
Copying multi-line wkt from a pdf for example creates carriage returns and line feeds in the WKT. When  pasting this multi-line WKT in the WKT field an error is displayed and the WKT is not displayed on the map.

A solution would be to replace any white space character like (spaces, tabs, and newlines) with a white space character. 
I've solved this issue in a fork and created pull request.

Example wkt that gave issues: POLYGON ((4.039569 50.938106, 4.039495 50.938106, 4.039471 50.938106, 4.039488 50.93791, 4.039488 50.937908, 4.03954
50.937913, 4.039591 50.937911, 4.039588 50.937978, 4.039575 50.937977, 4.039569 50.938106))

**Comment by pieterprovoost** [comment]
Thanks @koendecock, merged.
