### ISSUE TITLE
Feature: hash-based permalink

### ISSUE THREAD

**Issue by pietercolpaert** [pieterprovoost/wktmap#3]
## Why

I want to debug a geometry with my team by sharing a wktmap link

## Expected behaviour

 * Every time you click “Visualize” it should change the URL to `#crs=...&wkt=...` or `#wktLiteral=...` with these parameters filled out.
 * When loading the page and either crs, wkt or both, or wktLiteral are set, fill them out. Automatically visualize this without having to click the button

**Comment by pieterprovoost** [comment]
@pietercolpaert Does this work for you, so with parameters `wkt` and `epsg` corresponding to the current form fields?

https://wktmap.com/?wkt=MULTIPOLYGON+%28%28%28-4.1+48%2C+-4.1+47.9%2C+-3.45+47.7%2C+-3.15+47.8%2C+-3.14+47.5%2C+-2.93+47.7%2C+-2.69+47.6%2C+-2.91+47.6%2C+-2.82+47.5%2C+-2.23+47.6%2C+-2.5+47.5%2C+-2.55+47.3%2C+-2.43+47.3%2C+-2.19+47.2%2C+-2.25+47.1%2C+-1.98+47%2C+-2.14+46.8%2C+-1.81+46.5%2C+-1.09+46.3%2C+-1.24+46.2%2C+-0.991+46%2C+-1.17+45.9%2C+-1+45.7%2C+-1.21+45.8%2C+-1.23+45.7%2C+-0.799+45.5%2C+-0.617+45.1%2C+-0.146+44.8%2C+-0.607+45%2C+-0.333+44.6%2C+-0.51+44.7%2C+-0.803+45.3%2C+-1.13+45.5%2C+-1.26+44.6%2C+-1.17+44.8%2C+-1.02+44.7%2C+-1.26+44.5%2C+-1.53+43.5%2C+-1.19+43.5%2C+-2.13+43.3%2C+-2.75+43.5%2C+-2.98+43.3%2C+-3.48+43.4%2C+-3.59+43.5%2C+-4.57+43.4%2C+-5.84+43.7%2C+-7.05+43.5%2C+-7.69+43.8%2C+-7.9+43.7%2C+-4.1+48%29%29%29&epsg=4326

I agree in this case instant visualization makes sense, I'll look into that next.

**Comment by pieterprovoost** [comment]
Note that I implemented a length limit of 2000 characters, maybe this can be increased but I'll need to do some testing first.

**Comment by pietercolpaert** [comment]
This issue can be closed what I’m concerned

**Comment by pieterprovoost** [comment]
I finally managed to add a backend, there's a sharing button now which generates a short permalink.
