### ISSUE TITLE
Expose OpenLayers WKT parser error messages

### ISSUE THREAD

**Issue by pieterprovoost** [pieterprovoost/wktmap#7]
The OpenLayers WKT parser throws the errors below for unexpected tokens or invalid geomery types, these can be displayed instead of the generic parsing error (after removing the WKT part).

- https://github.com/openlayers/openlayers/blob/main/src/ol/format/WKT.js#L511
- https://github.com/openlayers/openlayers/blob/main/src/ol/format/WKT.js#L542

**Comment by pieterprovoost** [comment]
Fixed in https://github.com/pieterprovoost/wktmap/commit/684937bbd2c88fb87d1093c85aff80ac55b8e4b2

**Comment by pietercolpaert** [comment]
Nice! Useful!
